# Markov Chain Homework <br>
【教授】白惠明 <br>
【學生】711378912 蔡宜諠 <br>
【日期】2025/05/26 <br>

## ✅ HW1
A Markov chain $X_0, X_1, X_2, \ldots$ has the transition probability matrix:

$$
P =
\begin{bmatrix}
0.3 & 0.2 & 0.5 \\
0.5 & 0.1 & 0.4 \\
0.5 & 0.2 & 0.3
\end{bmatrix}
$$

Find all transition probabilities:

$$
P(X_5 = i \mid X_0 = j), \quad \text{for } i, j = 0, 1, 2
$$

*(use computer)*

In [5]:
import numpy as np

P = np.array([
    [0.3, 0.2, 0.5],
    [0.5, 0.1, 0.4],
    [0.5, 0.2, 0.3]
])

P5 = np.linalg.matrix_power(P, 5)
P5_rounded = np.round(P5, 4)
print('> result : ')
print(np.round(P5, 4))

print('\n> 分別輸出結果為: ')
# 印出每個 P(X_5 = i | X_0 = j)
for j in range(3):  # 初始狀態 X_0
    for i in range(3):  # 第五步狀態 X_5
        print(f"P(X₅ = {i} | X₀ = {j}) = {P5_rounded[j, i]}")

> result : 
[[0.4165 0.1818 0.4017]
 [0.4168 0.1818 0.4014]
 [0.4168 0.1818 0.4014]]

> 分別輸出結果為: 
P(X₅ = 0 | X₀ = 0) = 0.4165
P(X₅ = 1 | X₀ = 0) = 0.1818
P(X₅ = 2 | X₀ = 0) = 0.4017
P(X₅ = 0 | X₀ = 1) = 0.4168
P(X₅ = 1 | X₀ = 1) = 0.1818
P(X₅ = 2 | X₀ = 1) = 0.4014
P(X₅ = 0 | X₀ = 2) = 0.4168
P(X₅ = 1 | X₀ = 2) = 0.1818
P(X₅ = 2 | X₀ = 2) = 0.4014


---

<BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR>

## ✅ HW2 
一隻白老鼠被放置在如下圖所示的迷宮中：

<table>
  <tr>
    <td>0</td><td>1</td><td>7（food）</td>
  </tr>
  <tr>
    <td>2</td><td>3 老鼠起始點</td><td>4</td>
  </tr>
  <tr>
    <td>8（shock）</td><td>5</td><td>6</td>
  </tr>
</table>

假設白老鼠被放置在房間 3，每個門被選擇的機率相同。  
當老鼠進入 **房間 7（食物）** 或 **房間 8（電擊）**，實驗立即結束。


#### 問題：
1. 寫出 transition probability matrix  
2. 實驗結束時被電擊及得到食物的機率各為多少？ （列出方程組並用電腦求解）
3. 平均需要經過幾個房間實驗才能結束？

In [6]:
import numpy as np
import pandas as pd
from pprint import pprint
P = np.zeros((9, 9))

adjacency = {
    0: [1, 2], 1: [0, 3, 7], 2: [0, 3, 8], 3: [1, 2, 4, 5], 4: [3, 6, 7], 5: [3, 6, 8], 6: [4, 5],
    7: [7], 8: [8],  # 吸收狀態
}

# [ Q1 ]
for i in range(9):
    neighbors = adjacency[i]
    prob = 1 / len(neighbors)
    for j in neighbors:
        P[i][j] = prob

# Q2
Q = P[:7, :7]   # 取前 7 列、前 7 欄 → 暫態→暫態
R = P[:7, 7:]   # 取前 7 列、後 2 欄 → 暫態→吸收

I = np.eye(Q.shape[0])
N = np.linalg.inv(I - Q) # Fundamental matrix N = (I – Q)^{-1}
B = N @ R # B = N @ R

# 從房間 3 出發（index=3），
prob_food  = B[3, 0]  # B[3, 0] = 到達房間 7(food) 的機率
prob_shock = B[3, 1]  # B[3, 1] = 到達房間 8(shock) 的機率

# Q3
ones = np.ones((Q.shape[0], 1))  # 計算期望步數向量 t = N @ 1
t = N @ ones

print('> Q1 result：')  # 輸出
pprint(pd.DataFrame(np.round(P, 2), columns=[f's{j}' for j in range(9)], index=[f's{i}' for i in range(9)]))  # 轉移機率矩陣
print('\n> Q2 result：')
print(f"從房間 3 出發 → 吃到食物 (7) 的機率: {prob_food:.4f}")
print(f"從房間 3 出發 → 被電擊 (8) 的機率: {prob_shock:.4f}")
print('\n> Q3 result：')
print(f"從房間 3 出發 → 平均需要步數: {t[3, 0]:.0f}")

> Q1 result：
      s0    s1    s2    s3    s4    s5    s6    s7    s8
s0  0.00  0.50  0.50  0.00  0.00  0.00  0.00  0.00  0.00
s1  0.33  0.00  0.00  0.33  0.00  0.00  0.00  0.33  0.00
s2  0.33  0.00  0.00  0.33  0.00  0.00  0.00  0.00  0.33
s3  0.00  0.25  0.25  0.00  0.25  0.25  0.00  0.00  0.00
s4  0.00  0.00  0.00  0.33  0.00  0.00  0.33  0.33  0.00
s5  0.00  0.00  0.00  0.33  0.00  0.00  0.33  0.00  0.33
s6  0.00  0.00  0.00  0.00  0.50  0.50  0.00  0.00  0.00
s7  0.00  0.00  0.00  0.00  0.00  0.00  0.00  1.00  0.00
s8  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  1.00

> Q2 result：
從房間 3 出發 → 吃到食物 (7) 的機率: 0.5000
從房間 3 出發 → 被電擊 (8) 的機率: 0.5000

> Q3 result：
從房間 3 出發 → 平均需要步數: 6
