【課程名稱】<font color=#FF0000>機器學習(Machine Learning, ML)</font><br>
【授課講師】[陳祥輝 (mail : HsiangHui.Chen@gmail.com)](mailto:HsiangHui.Chen@gmail.com)<br>
【facebook】[陳祥輝老師的臉書 (歡迎加好友)](https://goo.gl/osivhx)<br>
【相關課程】[東吳推廣數位資訊學苑陳祥輝老師的課程表](https://www.ext.scu.edu.tw/courses_search.php?key=陳祥輝)<br>

【相關數據集】
- [威斯康星州數據集](https://archive.ics.uci.edu/ml/datasets.php) <font color=#FF0000>【★★★★★】有非常多的數據集可以下載</font>
- [威斯康星州乳腺癌數據集](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Prognostic%29)

<font color=#0000FF>【安裝主要的模組】</font>

In [1]:
# -*- coding: utf-8 -*-
from platform import python_version
import os, time, glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter

import sklearn
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model  import LogisticRegression

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.ensemble import RandomForestClassifier

print("【日期時間】{}".format(time.strftime("%Y/%m/%d %H:%M:%S")))
print("【工作目錄】{}".format(os.getcwd()))
print("【Python】{}".format(python_version()))
print("【sklearn】{}".format(sklearn.__version__))

【日期時間】2025/05/30 20:33:54
【工作目錄】d:\NTPU_class\ml\code
【Python】3.10.5
【sklearn】1.6.1


In [2]:
from matplotlib.font_manager import FontProperties  
winfont01 = FontProperties(fname=r"c:\windows\fonts\simsun.ttc", size=12) 
winfont02 = FontProperties(fname=r"c:\windows\fonts\kaiu.ttf", size=12) 

# plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei']  # 設定字型為微軟正黑體
# plt.rcParams['axes.unicode_minus'] = False                # 解決負號顯示問題

# macfont = FontProperties(fname="/Library/Fonts/Arial Unicode.ttf", size=10) 

【資料來源】[sklearn 中的 Pipeline 機制](https://www.itread01.com/content/1550014579.html)

<img src="http://180.218.162.136:2018/Images/PyML/sklearn_pipeline.png" width=400 align=left></img>

### <font color=#0000FF>資料集相關資訊</font>

威斯康辛乳腺癌診斷資料 : <https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data>

1. ID number
2. Diagnosis (M = malignant, B = benign) : （M =惡性，B =良性）

3-32 , Ten real-valued features are computed for each cell nucleus:

3. radius (mean of distances from center to points on the perimeter) : 半徑（從中心到外圍點的距離的平均值）
4. texture (standard deviation of gray-scale values) : 紋理（灰度值的標準偏差）
5. perimeter : 周長
6. area : 面積
7. smoothness (local variation in radius lengths) : 平滑度（半徑長度的局部變化）
8. compactness (perimeter^2 / area - 1.0) : 密實度（周長^ 2 /面積-1.0）
9. concavity (severity of concave portions of the contour) : 凹度（輪廓凹部的嚴重程度）
10. concave points (number of concave portions of the contour) : 凹點（輪廓的凹入部分的數量）
11. symmetry : 對稱
12. fractal dimension ("coastline approximation" - 1) : 分形維數（“海岸線近似”-1）

[sklearn 中的 Pipeline 機制](https://www.itread01.com/content/1550014579.html)

#### <font color=#0000FF>step 1 : 讀入資料</font>

In [3]:
uri = 'https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data'
df = pd.read_csv(uri, header=None)
print(df.shape)

X, y = df.to_numpy()[:, 2:], df.to_numpy()[:, 1]    # y為字元型標籤
print(Counter(y))

(569, 32)
Counter({'B': 357, 'M': 212})


#### <font color='gray'>(Optional) step 2 : 轉換類別型資料的 y 值為 0, 1, 2, ....</font>

In [4]:
encoder = LabelEncoder()       # 使用LabelEncoder類將其轉換為0開始的數值型
y = encoder.fit_transform(y)   # .fit_transform(y) 等同於先後做 (1) .fit(y) (2) .transform(y)
#1. encoder.fit(y)                            
#2. encoder.transform(y)

print(Counter(y))

Counter({np.int64(0): 357, np.int64(1): 212})


#### <font color=#0000FF>step 3 : 切割資料集</font>

In [5]:
X_train, X_test, y_train, y_test = \
        train_test_split(X, y, test_size=.2, random_state=None)

#### <font color=#0000FF>step 4 : 將 X 標準化</font>

In [6]:
print('Before : \n', X_train)
print('shape of X_train : \n', X_train.shape)

scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.fit_transform(X_test)

print('After : \n', X_train)
print('shape of X_train : \n', X_train.shape)

Before : 
 [[19.53 18.9 129.5 ... 0.198 0.2968 0.09929]
 [12.56 19.07 81.92 ... 0.09265 0.2121 0.07188]
 [13.87 16.21 88.52 ... 0.05556 0.2362 0.07113]
 ...
 [7.729 25.49 47.98 ... 0.0 0.3058 0.09938]
 [11.76 18.14 75.0 ... 0.0716 0.1978 0.06915]
 [12.0 28.23 76.77 ... 0.07116 0.2447 0.08194]]
shape of X_train : 
 (455, 30)
After : 
 [[ 1.50552363 -0.11355761  1.51135005 ...  1.231026    0.08664798
   0.82077437]
 [-0.4437736  -0.07364993 -0.41443031 ... -0.34090715 -1.24773095
  -0.67639966]
 [-0.0774064  -0.74503803 -0.1472981  ... -0.89432908 -0.86805524
  -0.71736575]
 ...
 [-1.79485753  1.43345204 -1.78813745 ... -1.7233429   0.22843559
   0.8256903 ]
 [-0.6675093  -0.29196844 -0.69451438 ... -0.65499536 -1.4730157
  -0.82551623]
 [-0.60038859  2.07667002 -0.62287438 ... -0.66156062 -0.73414472
  -0.12690784]]
shape of X_train : 
 (455, 30)


#### <font color=#0000FF>step 5 : 使用 PCA 將 X_test 降維</font>

In [7]:
print('Before : shape of X_train : {}'.format(X_train.shape))
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)
print('After : shape of X_train : {}'.format(X_train.shape))

Before : shape of X_train : (455, 30)
After : shape of X_train : (455, 2)


#### <font color=#0000FF>step 6 : 建模</font>

In [8]:
lr = LogisticRegression(random_state=1)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9649122807017544

#### <font color=#0000FF>step 7 : 預測</font>

In [9]:
lr.predict(X_test)

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0])

### <font color=#FF0000>將以上 step 4 ~ step 7 的過程打包成一個 pipeline

#### <font color=blue>使用 sklearn.pipeline.Pipeline 類別</font>

In [12]:
# 他就是一個管道的概念
from sklearn.pipeline import Pipeline  # 建議用類別的部分

In [11]:
%%time
# 1.讀取資料檔案，以及前置處理
uri = 'https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data'
df = pd.read_csv(uri, header=None)
X, y = df.values[:, 2:], df.values[:, 1]    # y為字元型標籤

# encoder = LabelEncoder()
# y = encoder.fit_transform(y)   # (Optional)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=0)

#----------#----------#----------#----------#----------#----------#----------#----------#

# 2.建置 pipeline 
pipeline = Pipeline([("scaler", StandardScaler()),             # step 4
                     ("pca", PCA(n_components=2)),             # step 5
                     ("model", LogisticRegression())],)        # step 6

# 3.配適與正確率評估
pipeline.fit(X_train, y_train)
print(f"train acc : {pipeline.score(X_train, y_train):.3f}")
print(f"test acc : {pipeline.score(X_test, y_test):.3f}")

# 4.預測
pipeline.predict(X_test)

train acc : 0.967
test acc : 0.921
CPU times: total: 46.9 ms
Wall time: 892 ms


array(['M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B',
       'M', 'M', 'M', 'B', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'M', 'B',
       'B', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'B',
       'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'M',
       'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'M',
       'B', 'M', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B',
       'M', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B'], dtype=object)

#### <font color=blue>細部探討 Pipeline 內的每一個物件，以及其method(s)</font>

In [13]:
Pipeline([('sc', StandardScaler()), 
          ('pca', PCA(n_components=2)), 
          ('clf', LogisticRegression(random_state=1))])

Pipeline(steps=[('sc', StandardScaler()), ('pca', PCA(n_components=2)),
                ('clf', LogisticRegression(random_state=1))])

In [15]:
print("---【列出pipeline裡面的steps】----------------------")
print(pipeline)
print("---【取出pipeline裡面的特定物件】----------------------")
print(pipeline["scaler"])
print(pipeline["pca"])
print(pipeline["model"])
print("---【使用pipeline裡面個別的物件】----------------------")
print(type(pipeline["scaler"]))
pipeline["scaler"].fit_transform(X_test)

---【列出pipeline裡面的steps】----------------------
Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('model', LogisticRegression())])
---【取出pipeline裡面的特定物件】----------------------
StandardScaler()
PCA(n_components=2)
LogisticRegression()
---【使用pipeline裡面個別的物件】----------------------
<class 'sklearn.preprocessing._data.StandardScaler'>


array([[-0.22609091,  0.14299357, -0.16219992, ...,  1.33438591,
         1.22101459,  1.32977555],
       [-0.28072076,  1.13113906, -0.34954245, ..., -0.81952682,
        -0.77541863, -0.94570364],
       [-0.04782508, -0.87231025, -0.12299829, ..., -0.49120548,
        -1.31433312, -0.98696059],
       ...,
       [ 1.7233322 , -0.06173848,  1.70132185, ...,  1.51554921,
         0.25341812, -0.26496405],
       [ 1.18565945,  0.15552818,  1.16487847, ...,  0.53103066,
         0.32690646, -0.37709831],
       [ 0.24545096, -0.64668718,  0.25416267, ..., -0.19956228,
        -1.2425945 , -0.01424877]], shape=(114, 30))

### <font color=#0000FF>堆疊多個 Pipelines，用以找到最佳的模型</font>

In [16]:
%%time
pipeline_lr=Pipeline([('scaler'         , StandardScaler()),
                      ('pca'            , PCA(n_components=2)), 
                      ('estimator'      , LogisticRegression())])
pipeline_dt=Pipeline([('scaler'         , StandardScaler()),
                      ('pca'            , PCA(n_components=2)),
                      ('estimator'      , DecisionTreeClassifier())])
pipeline_rf = Pipeline([('scaler'       , StandardScaler()),
                        ('pca'          , PCA(n_components=2)),
                        ('estimator'    , RandomForestClassifier())])
pipeline_knn=Pipeline([('scaler'        , StandardScaler()),
                       ('pca'           , PCA(n_components=2)),
                       ('estimator'     , KNeighborsClassifier())])

pipelines = [pipeline_lr, 
             pipeline_dt, 
             pipeline_rf, 
             pipeline_knn]

#----------#----------#----------#----------#----------#----------#----------#----------#

for idx, pipeline in enumerate(pipelines, start=1) :
    print(f"【{idx}】{pipeline['estimator'].__class__.__name__}")
    print(pipeline.named_steps)
    pipeline.fit(X_train, y_train)
    print(f"train acc : {pipeline.score(X_train, y_train):.3%}")
    print(f"test acc : {pipeline.score(X_test, y_test):.3%}\n")

【1】LogisticRegression
{'scaler': StandardScaler(), 'pca': PCA(n_components=2), 'estimator': LogisticRegression()}
train acc : 96.703%
test acc : 92.105%

【2】DecisionTreeClassifier
{'scaler': StandardScaler(), 'pca': PCA(n_components=2), 'estimator': DecisionTreeClassifier()}
train acc : 100.000%
test acc : 92.105%

【3】RandomForestClassifier
{'scaler': StandardScaler(), 'pca': PCA(n_components=2), 'estimator': RandomForestClassifier()}
train acc : 100.000%
test acc : 92.105%

【4】KNeighborsClassifier
{'scaler': StandardScaler(), 'pca': PCA(n_components=2), 'estimator': KNeighborsClassifier()}
train acc : 95.165%
test acc : 92.105%

CPU times: total: 172 ms
Wall time: 153 ms
